/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_grafica;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import controller.ManterAlunoController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import to.AlunoTransferObject;
import view.FacadeAlunoController;

/**
 *
 * @author ymbere
 */
public class Crud_aluno extends javax.swing.JFrame {
    
    
    public void popupaTabela(){
        FacadeAlunoController alunoController = new ManterAlunoController();
        ArrayList<AlunoTransferObject> alunos = alunoController.retornaAlunos();
        
        
        DefaultTableModel model = (DefaultTableModel) table_aluno.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[2];
        for (int i = 0; i < alunos.size(); i++) {
            rowData[0] = alunos.get(i).getNome();
            rowData[1] = alunos.get(i).getRg();
            model.addRow(rowData);
            
        }
    }

    /**
     * Creates new form Crud_aluno
     */
    public Crud_aluno() {
        initComponents();
        popupaTabela();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        table_aluno = new javax.swing.JTable();
        btn_apagar = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();
        btn_inserirLinha = new javax.swing.JButton();
        lbl_rg = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        lbl_nome = new javax.swing.JLabel();
        txt_rg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_aluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "RG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_aluno);

        btn_apagar.setText("Apagar");
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });

        btn_atualizar.setText("Atualizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        btn_inserirLinha.setText("Insere Linha");
        btn_inserirLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirLinhaActionPerformed(evt);
            }
        });

        lbl_rg.setText("RG");

        txt_nome.setText("jTextField1");

        lbl_nome.setText("Nome");

        txt_rg.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_apagar)
                        .addGap(34, 34, 34)
                        .addComponent(btn_atualizar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_nome)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_rg)
                                .addGap(36, 36, 36)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_inserirLinha)
                        .addGap(149, 149, 149)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_apagar)
                    .addComponent(btn_atualizar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nome)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_rg)
                            .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_inserirLinha)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_aluno.getModel();
        
        int row = table_aluno.getSelectedRow();
        System.out.println(row);
                
        
        String selected = model.getValueAt(row, 1).toString();
        
        if (row >= 0){
            try {
                FacadeAlunoController alunoController = new ManterAlunoController();
                alunoController.deletar_aluno(selected);
                System.out.println(selected);
                popupaTabela();
                
            } catch (Exception e) {
               JOptionPane.showMessageDialog(this, "Error");
            }
            
        }
        
        
        
    }//GEN-LAST:event_btn_apagarActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_aluno.getModel();
        
        int row = table_aluno.getSelectedRow();
        System.out.println(row);
        
        String nome = model.getValueAt(row,0).toString();
        System.out.println(nome);        
        String rg = model.getValueAt(row, 1).toString();
        System.out.println(rg);
        
        if (row >= 0) {
            try {
                FacadeAlunoController alunoController = new ManterAlunoController();
                AlunoTransferObject alunoAtualizado = new AlunoTransferObject();
                alunoAtualizado.setNome(nome);
                alunoAtualizado.setRg(rg);
                alunoController.editar_aluno(rg, alunoAtualizado);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error");
            }
        }
        
        
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void btn_inserirLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirLinhaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_aluno.getModel();
        FacadeAlunoController alunoController = new ManterAlunoController();
        
        AlunoTransferObject alunoTransferObject = new AlunoTransferObject();
        
        alunoTransferObject.setNome(txt_nome.getText());
        alunoTransferObject.setRg(txt_rg.getText());
        
        try {
            alunoController.cadastrar_aluno(alunoTransferObject);
            popupaTabela();            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
         
        
       
  

       
    }//GEN-LAST:event_btn_inserirLinhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud_aluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_inserirLinha;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_nome;
    private javax.swing.JLabel lbl_rg;
    private javax.swing.JTable table_aluno;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_rg;
    // End of variables declaration//GEN-END:variables
}
