/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view_grafica;

import controller.ManterAlunoController;
import controller.ManterProfessorController;
import controller.ManterProjetoController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import to.ProjetoTransferObject;
import view.FacadeAlunoController;
import view.FacadeProfessorController;
import view.FacadeProjetoController;

/**
 *
 * @author ymbere
 */
public class Crud_projeto extends javax.swing.JFrame {
    
    public void populaTabela(){
        FacadeProjetoController projetoController = new ManterProjetoController();
        ArrayList<ProjetoTransferObject> projetos = projetoController.ordenaERetorna();
        
        int projetosSize = projetos.size();
        String temp1;
        String temp2;
        
        DefaultTableModel model = (DefaultTableModel) table_projeto.getModel();
        model.setRowCount(0);
        
        Object rowData[] = new Object[4];   
        Object empty[] = {"---","---","---"};
        for (int i = 0; i < projetosSize; i++){

            int j = i;
            int repeticao = 0;

            while (true){
                temp1 = projetos.get(j).getOrientador().getNome();
                if (j+1 == projetosSize){
                    break;
                }
                else {
                    temp2 = projetos.get(j+1).getOrientador().getNome();
                }
                if (temp1.equals(temp2)){
                    repeticao++;
                    j++;
                }
                else {
                    break;
                }
            }

            rowData[0] = projetos.get(i).getOrientador().getNome();
            rowData[1] = "";
            rowData[2] = "";
            rowData[3] = "";
            model.addRow(rowData);
            model.addRow(empty);

            int x = i;
            i = i +repeticao;
            while (repeticao >= 0){
                rowData[0] = "";
                rowData[1] = projetos.get(x).getTitulo();
                rowData[2] = projetos.get(x).getOrientado().getNome();
                rowData[3] = projetos.get(x).getResumo();
                model.addRow(rowData);                
                x++;
                repeticao--;
            }
            model.addRow(empty);
        }        
        
    }

    /**
     * Creates new form Crud_projeto
     */
    public Crud_projeto() {
        initComponents();
        populaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_projeto = new javax.swing.JTable();
        btn_apagar = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();
        lbl_professor = new javax.swing.JLabel();
        lbl_tituloProjeto = new javax.swing.JLabel();
        lbl_orientado = new javax.swing.JLabel();
        txt_professor = new javax.swing.JTextField();
        txt_tituloProjeto = new javax.swing.JTextField();
        txt_aluno = new javax.swing.JTextField();
        btn_inserirLinha = new javax.swing.JButton();
        lbl_resumo = new javax.swing.JLabel();
        txt_resumo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        table_projeto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Professor", "Titulo do Projeto", "Orientado", "Resumo"
            }
        ));
        jScrollPane1.setViewportView(table_projeto);

        btn_apagar.setText("Apagar");
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });

        btn_atualizar.setText("Atulizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        lbl_professor.setText("Professor");

        lbl_tituloProjeto.setText("Titulo Projeto");

        lbl_orientado.setText("Orientado");

        txt_professor.setText("jTextField1");

        txt_tituloProjeto.setText("jTextField2");

        txt_aluno.setText("jTextField3");

        btn_inserirLinha.setText("Inserir Linha");
        btn_inserirLinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirLinhaActionPerformed(evt);
            }
        });

        lbl_resumo.setText("Resumo");

        txt_resumo.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_resumo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_resumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbl_orientado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbl_tituloProjeto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_tituloProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbl_professor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn_apagar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_atualizar)))
                        .addGap(35, 35, 35)
                        .addComponent(btn_inserirLinha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_apagar)
                    .addComponent(btn_atualizar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_professor)
                    .addComponent(txt_professor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_tituloProjeto)
                            .addComponent(txt_tituloProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_orientado)
                            .addComponent(txt_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_inserirLinha)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_resumo)
                    .addComponent(txt_resumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Menu_principal menu = new Menu_principal();
        menu.setVisible(true);                   
        System.out.println("Fechando");
    }//GEN-LAST:event_formWindowClosing

    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_projeto.getModel();
        
        int row = table_projeto.getSelectedRow();
        System.out.println(row);
        
        String selected = model.getValueAt(row, 1).toString();
        
        if (row >= 0) {
            try {
                FacadeProjetoController projetoController = new ManterProjetoController();
                projetoController.deletaProjeto(selected);
                System.out.println(selected);
                populaTabela();                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error");
            }
        }
        
        
    }//GEN-LAST:event_btn_apagarActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_projeto.getModel();
        
        int row = table_projeto.getSelectedRow();
        String substr = ",";
        String[] parts;
        System.out.println(row);
     
        
        String professor = model.getValueAt(row, 0).toString();
        System.out.println(professor);
        
        String tituloProjetoTotal = model.getValueAt(row, 1).toString();
        parts = tituloProjetoTotal.split(substr);
        String tituloAntes = parts[0];
        String tituloDepois = parts[1];       
        System.out.println("Titulo de: " + tituloAntes + " Para: " + tituloDepois);
        
        String aluno = model.getValueAt(row, 2).toString();
        System.out.println(aluno);
        
        String resumo = model.getValueAt(row, 3).toString();
        System.out.println(resumo);
        
        if (row >= 0) {
            try {
                FacadeProjetoController projetoController = new ManterProjetoController();
                FacadeAlunoController alunoController = new ManterAlunoController();
                FacadeProfessorController professorController = new ManterProfessorController();
                
                ProjetoTransferObject projetoTransferObject = new ProjetoTransferObject();
                
                projetoTransferObject.setTitulo(tituloDepois);
                projetoTransferObject.setResumo(resumo);
                projetoTransferObject.setOrientado(alunoController.retorna_aluno(aluno));
                projetoTransferObject.setOrientador(professorController.retornaProfessor(professor));
                
                projetoController.editarProjeto(tituloAntes, projetoTransferObject);
                
                populaTabela();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error");
            }
            
        }
        
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void btn_inserirLinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirLinhaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_projeto.getModel();
        
        FacadeProjetoController projetoController = new ManterProjetoController();
        FacadeAlunoController alunoController = new ManterAlunoController();
        FacadeProfessorController professorController = new ManterProfessorController();
        
        ProjetoTransferObject projetoTransferObject = new ProjetoTransferObject();
        
        projetoTransferObject.setTitulo(txt_tituloProjeto.getText());
        projetoTransferObject.setResumo(txt_resumo.getText());
        projetoTransferObject.setOrientado(alunoController.retorna_aluno(txt_aluno.getText()));
        projetoTransferObject.setOrientador(professorController.retornaProfessor(txt_professor.getText()));
        
        try {
            projetoController.cadastrarProjeto(projetoTransferObject);
            populaTabela();;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
        
    }//GEN-LAST:event_btn_inserirLinhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_projeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_projeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_projeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_projeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crud_projeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_inserirLinha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_orientado;
    private javax.swing.JLabel lbl_professor;
    private javax.swing.JLabel lbl_resumo;
    private javax.swing.JLabel lbl_tituloProjeto;
    private javax.swing.JTable table_projeto;
    private javax.swing.JTextField txt_aluno;
    private javax.swing.JTextField txt_professor;
    private javax.swing.JTextField txt_resumo;
    private javax.swing.JTextField txt_tituloProjeto;
    // End of variables declaration//GEN-END:variables
}
